# Site settings
title: Policy Models Tutorial
author: Shelly Talis
email: shellytalis@gmail.com
description: "Great tutorial about policy model web component."

# Build settings . jekyll-theme-tactile
theme: minima
